# Generated by Django 3.1.5 on 2021-01-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('nickname', models.CharField(max_length=128, unique=True, verbose_name='Nickname')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Season Number')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.IntegerField(verbose_name='Played')),
                ('wins', models.IntegerField(verbose_name='Wins')),
                ('losses', models.IntegerField(verbose_name='Losses')),
                ('goals_forced', models.IntegerField(verbose_name='Goals Forced')),
                ('goals_allowed', models.IntegerField(verbose_name='Goals Allowed')),
                ('goal_differential', models.IntegerField(verbose_name='Goal Differential')),
                ('power_index', models.FloatField(verbose_name='Power Index')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fball_app.player', verbose_name='Player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fball_app.season', verbose_name='Season')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_score', models.IntegerField(verbose_name='Winning Score')),
                ('losing_score', models.IntegerField(verbose_name='Losing Score')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('loser', models.ForeignKey(db_column='game_loser', on_delete=django.db.models.deletion.CASCADE, related_name='game_loser', to='fball_app.player', verbose_name='Loser')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fball_app.season', verbose_name='Season')),
                ('winner', models.ForeignKey(db_column='game_winner', on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='fball_app.player', verbose_name='Winner')),
            ],
        ),
    ]
